version: '3.1'
services:
  app-pm2:
      container_name: app-pm2
      #构建容器
      build: ./project
      #直接从git拉去
      # build: git@github.com:su37josephxia/docker_ci.git#:backend
      # 需要链接本地代码时
      volumes:
        # - ./project:/usr/src/app
        - ./nginx/conf.d/:/etc/nginx/conf.d
      ports:
        - "3000:3000"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always 
    ports:
      - 8081:8081
 
      